name: Basic role syntax check
on:
  push:
    branches:
      - master

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create ansible.cfg with correct roles_path
        run: printf '[defaults]\nroles_path=../' >ansible.cfg

      - name: Basic role syntax check
        run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check
