name: Basic role syntax check
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 2.7.18
        uses: actions/setup-python@v1
        with:
          python-version: 2.7.18

      - name: Install ansible
        run: pip install --upgrade pip ansible

      - name: Check ansible version
        run: ansible --version

      - name: Create ansible.cfg with correct roles_path
        run: printf '[defaults]\nroles_path=../' >ansible.cfg

      - name: Basic role syntax check
        run:  ansible-playbook tests/test.yml -i tests/inventory --syntax-check
